package com.tf.core_service.request;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tf.core_service.model.fabrication.Printouts;
import com.tf.core_service.model.fabrication.Stiffner;
import com.tf.core_service.model.twoWindings.ETransBodyType;
import com.tf.core_service.model.twoWindings.ETransCostType;
import com.tf.core_service.model.twoWindings.EVectorGroup;
import lombok.Data;

import java.util.ArrayList;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class FabricationRequest {
    public String designId;
    public Integer kVA;
    public Integer tank_L;
    public Integer tank_W;
    public Integer tank_H;
    public Integer tank_Thick;
    public Integer tank_Bot_Thick;
    public Integer tank_Flg_Thick;
    public Integer radiator_CC;
    public Integer radiator_W;
    public Integer radiator_Fin_Nos;
    public Integer radiator_Nos;
    public Integer lid_Thick;
    public Integer hvb_Volt;  //hv bushing
    public Integer hvb_Amp;
    public Integer lvb_Volt;
    public Integer lvb_Amp;
    public Integer cons_Vol;
    public Integer cons_Dia;
    public Integer cons_L;
    public Integer transformer_Weight;
    public Integer core_Dia;
    public Integer limb_CC;
    public Integer limb_Nos;
    public Boolean yoke_Holes;
    public Double lv_Cond_W;
    public Double lv_Cond_H;
    public Double lv_Cond_Rad;
    public Double lv_Cond_Ax;
    public Double lv_Volts;
    public Double lv_ID;
    public Double lv_OD;
    public Double lv_Wdg_L;
    public Double hv_ID;
    public Double hv_OD;
    public Double hv_Wdg_L;
    public Double limb_H;
//    public String core_Fixture_Type;
    public Integer radiator_Left_Nos;
    public Integer radiator_Right_Nos;
    public String hvb_Pos;
    public String lvb_Pos;
    public String hvb_Type;
    public String lvb_Type;
    public Double current;
    public Double hvb_F_Tilt_Ang;
    public String hvb_Sup_type;
    public String lvb_Sup_type;
    public String stiffner_Hori_Nos_Calc_Mode;
    public String stiffner_Vert_Nos_Calc_Mode;
    public String radiator_Type;
    public String rad_Ptch_Calc_Mode;
    public Integer radiator_Min_Gap;
    public Boolean drain_Vlv;
    public Integer drain_Vlv_Nos;
    public Boolean smpl_Vlv;
    public Integer smpl_Vlv_Nos;
    public Boolean fill_Vlv;
    public Boolean tank_LiftLug;
    public Boolean hvcb;
    public String hvcb_Pos;
    public Boolean lvcb;
    public Integer mog_Tlt_Ang;
    public Boolean roller;
    public String roller_Type;
    public Boolean thermoPkt1;
    public Boolean thermoPkt2;
    public Boolean exp_Vent;
    public Boolean exp_Vent_With_OI;
    public Boolean isRoller;
    public Stiffner stiffner;
    public Boolean isOCTC;
    public EVectorGroup eVectorGroup;
    public Boolean buchholz_Relay;
    public Boolean single_Valve;
    public Boolean valve_Type1;
    public Boolean marshBox;
    public Boolean mog;
    public Double tapStepPercentage;
    public ArrayList<Integer> turnsPerTap;
    public ArrayList<Integer> tapVoltages;
    public ArrayList<Double> tapCurrent;
    public Printouts printouts;
    public Boolean radiator_Vlv;
}
